//******************************************************************************
//  _____                  _    _             __
// |  _  |                | |  | |           / _|
// | | | |_ __   ___ _ __ | |  | | __ _ _ __| |_ __ _ _ __ ___
// | | | | '_ \ / _ \ '_ \| |/\| |/ _` | '__|  _/ _` | '__/ _ \
// \ \_/ / |_) |  __/ | | \  /\  / (_| | |  | || (_| | | |  __/
//  \___/| .__/ \___|_| |_|\/  \/ \__,_|_|  |_| \__,_|_|  \___|
//       | |               We don't make the game you play.
//       |_|                 We make the game you play BETTER.
//
//            Website: http://openwarfaremod.com/
//******************************************************************************

#include openwarfare\_utils;

init()
{
	//******************************************************************************
	// configs/gameplay/classes.cfg
	//******************************************************************************	
	// setDvar( "class_grenadier_movespeed", "0.95" );
	// setDvar( "class_rifleman_movespeed", "0.95" );
	// setDvar( "class_lightgunner_movespeed", "1.00" );
	// setDvar( "class_heavygunner_movespeed", "0.875" );
	// setDvar( "class_closeassault_movespeed", "1.00" );
	// setDvar( "class_sniper_movespeed", "1.00" );
	// setDvar( "scr_satchel_ammo_count", "2" );
	// setDvar( "scr_betty_ammo_count", "2" );
	// setDvar( "scr_bazooka_ammo_count", "2" );
	// setDvar( "class_allies_grenadier_limit", "64" );
	// setDvar( "class_allies_rifleman_limit", "64" );
	// setDvar( "class_allies_lightgunner_limit", "64" );
	// setDvar( "class_allies_heavygunner_limit", "64" );
	// setDvar( "class_allies_closeassault_limit", "64" );
	// setDvar( "class_allies_sniper_limit", "64" );
	// setDvar( "class_axis_grenadier_limit", "64" );
	// setDvar( "class_axis_rifleman_limit", "64" );
	// setDvar( "class_axis_lightgunner_limit", "64" );
	// setDvar( "class_axis_heavygunner_limit", "64" );
	// setDvar( "class_axis_closeassault_limit", "64" );
	// setDvar( "class_axis_sniper_limit", "64" );
	// setDvar( "attach_gl_limit", "64" );
	// setDvar( "m8_white_smoke_limit", "64" );
	// setDvar( "class_grenadier_allowdrop", "1" );
	// setDvar( "class_rifleman_allowdrop", "1" );
	// setDvar( "class_lightgunner_allowdrop", "1" );
	// setDvar( "class_heavygunner_allowdrop", "1" );
	// setDvar( "class_closeassault_allowdrop", "1" );
	// setDvar( "class_sniper_allowdrop", "1" );
	// setDvar( "scr_frag_grenades_allowdrop", "0" );
	// setDvar( "scr_sticky_grenades_allowdrop", "0" );
	// setDvar( "scr_molotovs_allowdrop", "0" );
	// setDvar( "scr_tabun_gas_grenades_allowdrop", "0" );
	// setDvar( "scr_signal_flares_allowdrop", "0" );
	// setDvar( "scr_smoke_grenades_allowdrop", "0" );
	// setDvar( "weap_allow_colt", "1" );
	// setDvar( "weap_allow_nambu", "1" );
	// setDvar( "weap_allow_walther", "1" );
	// setDvar( "weap_allow_tokarev", "1" );
	// setDvar( "weap_allow_357magnum", "1" );
	// setDvar( "weap_allow_binoculars", "0" );
	// setDvar( "weap_allow_frag_grenade", "1" );
	// setDvar( "weap_allow_sticky_grenade", "1" );
	// setDvar( "weap_allow_molotov", "1" );
	// setDvar( "weap_allow_tabun_gas", "1" );
	// setDvar( "weap_allow_signal_flare", "1" );
	// setDvar( "weap_allow_m8_white_smoke", "1" );
	// setDvar( "weap_allow_grenadier_springfield", "1" );
	// setDvar( "weap_allow_grenadier_type99rifle", "1" );
	// setDvar( "weap_allow_grenadier_mosinrifle", "1" );
	// setDvar( "weap_allow_grenadier_kar98k", "1" );
	// setDvar( "attach_allow_grenadier_none", "1" );
	// setDvar( "attach_allow_grenadier_bayonet", "1" );
	// setDvar( "attach_allow_grenadier_gl", "1" );
	// setDvar( "class_grenadier_primary", "springfield;springfield;type99rifle;springfield;mosinrifle;kar98k;type99rifle" );
	// setDvar( "class_grenadier_primary_attachment", "bayonet" );
	// setDvar( "class_grenadier_secondary", "colt;colt;walther;colt;tokarev;walther;nambu" );
	// setDvar( "class_grenadier_perk1", "satchel_charge_mp" );
	// setDvar( "class_grenadier_perk2", "specialty_bulletdamage" );
	// setDvar( "class_grenadier_perk3", "specialty_longersprint" );
	// setDvar( "class_grenadier_perk4", "specialty_water_cooled" );
	// setDvar( "class_grenadier_pgrenade", "frag_grenade" );
	// setDvar( "class_grenadier_sgrenade", "signal_flare" );
	// setDvar( "class_grenadier_pgrenade_count", "1" );
	// setDvar( "class_grenadier_sgrenade_count", "1" );
	// setDvar( "class_grenadier_lock_primary", "0" );
	// setDvar( "class_grenadier_lock_primary_attachment", "0" );
	// setDvar( "class_grenadier_lock_secondary", "0" );
	// setDvar( "class_grenadier_lock_perk1", "0" );
	// setDvar( "class_grenadier_lock_perk2", "0" );
	// setDvar( "class_grenadier_lock_perk3", "0" );
	// setDvar( "class_grenadier_lock_perk4", "0" );
	// setDvar( "class_grenadier_lock_pgrenade", "0" );
	// setDvar( "class_grenadier_lock_sgrenade", "0" );
	// setDvar( "weap_allow_rifleman_svt40", "1" );
	// setDvar( "weap_allow_rifleman_gewehr43", "1" );
	// setDvar( "weap_allow_rifleman_m1garand", "1" );
	// setDvar( "weap_allow_rifleman_m1carbine", "1" );
	// setDvar( "attach_allow_rifleman_none", "1" );
	// setDvar( "attach_allow_rifleman_aperture", "1" );
	// setDvar( "attach_allow_rifleman_bayonet", "1" );
	// setDvar( "attach_allow_rifleman_bigammo", "1" );
	// setDvar( "attach_allow_rifleman_flash", "1" );
	// setDvar( "attach_allow_rifleman_silenced", "1" );
	// setDvar( "attach_allow_rifleman_telescopic", "1" );
	// setDvar( "attach_allow_rifleman_gl", "1" );
	// setDvar( "class_rifleman_primary", "svt40;m1garand;gewehr43;m1garand;svt40;gewehr43;none" );
	// setDvar( "class_rifleman_primary_attachment", "none" );
	// setDvar( "class_rifleman_secondary", "colt;colt;walther;colt;tokarev;walther;nambu" );
	// setDvar( "class_rifleman_perk1", "satchel_charge_mp" );
	// setDvar( "class_rifleman_perk2", "specialty_bulletdamage" );
	// setDvar( "class_rifleman_perk3", "specialty_longersprint" );
	// setDvar( "class_rifleman_perk4", "specialty_water_cooled" );
	// setDvar( "class_rifleman_pgrenade", "frag_grenade" );
	// setDvar( "class_rifleman_sgrenade", "signal_flare" );
	// setDvar( "class_rifleman_pgrenade_count", "1" );
	// setDvar( "class_rifleman_sgrenade_count", "1" );
	// setDvar( "class_rifleman_lock_primary", "0" );
	// setDvar( "class_rifleman_lock_primary_attachment", "0" );
	// setDvar( "class_rifleman_lock_secondary", "0" );
	// setDvar( "class_rifleman_lock_perk1", "0" );
	// setDvar( "class_rifleman_lock_perk2", "0" );
	// setDvar( "class_rifleman_lock_perk3", "0" );
	// setDvar( "class_rifleman_lock_perk4", "0" );
	// setDvar( "class_rifleman_lock_pgrenade", "0" );
	// setDvar( "class_rifleman_lock_sgrenade", "0" );
	// setDvar( "weap_allow_lightgunner_thompson", "1" );
	// setDvar( "weap_allow_lightgunner_mp40", "1" );
	// setDvar( "weap_allow_lightgunner_type100smg", "1" );
	// setDvar( "weap_allow_lightgunner_ppsh", "1" );
	// setDvar( "weap_allow_lightgunner_stg44", "1" );
	// setDvar( "attach_allow_lightgunner_none", "1" );
	// setDvar( "attach_allow_lightgunner_aperture", "1" );
	// setDvar( "attach_allow_lightgunner_bigammo", "1" );
	// setDvar( "attach_allow_lightgunner_flash", "1" );
	// setDvar( "attach_allow_lightgunner_silenced", "1" );
	// setDvar( "attach_allow_lightgunner_telescopic", "1" );
	// setDvar( "class_lightgunner_primary", "thompson;thompson;mp40;thompson;ppsh;mp40;type100smg" );
	// setDvar( "class_lightgunner_primary_attachment", "none" );
	// setDvar( "class_lightgunner_secondary", "colt;colt;walther;colt;tokarev;walther;nambu" );
	// setDvar( "class_lightgunner_perk1", "specialty_specialgrenade" );
	// setDvar( "class_lightgunner_perk2", "specialty_gas_mask" );
	// setDvar( "class_lightgunner_perk3", "specialty_bulletaccuracy" );
	// setDvar( "class_lightgunner_perk4", "specialty_water_cooled" );
	// setDvar( "class_lightgunner_pgrenade", "frag_grenade" );
	// setDvar( "class_lightgunner_sgrenade", "signal_flare" );
	// setDvar( "class_lightgunner_pgrenade_count", "1" );
	// setDvar( "class_lightgunner_sgrenade_count", "1" );
	// setDvar( "class_lightgunner_lock_primary", "0" );
	// setDvar( "class_lightgunner_lock_primary_attachment", "0" );
	// setDvar( "class_lightgunner_lock_secondary", "0" );
	// setDvar( "class_lightgunner_lock_perk1", "0" );
	// setDvar( "class_lightgunner_lock_perk2", "0" );
	// setDvar( "class_lightgunner_lock_perk3", "0" );
	// setDvar( "class_lightgunner_lock_perk4", "0" );
	// setDvar( "class_lightgunner_lock_pgrenade", "0" );
	// setDvar( "class_lightgunner_lock_sgrenade", "0" );
	// setDvar( "weap_allow_heavygunner_type99lmg", "1" );
	// setDvar( "weap_allow_heavygunner_bar", "1" );
	// setDvar( "weap_allow_heavygunner_dp28", "1" );
	// setDvar( "weap_allow_heavygunner_mg42", "1" );
	// setDvar( "weap_allow_heavygunner_fg42", "1" );
	// setDvar( "weap_allow_heavygunner_30cal", "1" );
	// setDvar( "attach_allow_heavygunner_none", "1" );
	// setDvar( "attach_allow_heavygunner_bayonet", "1" );
	// setDvar( "attach_allow_heavygunner_bipod", "1" );
	// setDvar( "attach_allow_heavygunner_telescopic", "1" );
	// setDvar( "class_heavygunner_primary", "type99lmg;bar;type99lmg;bar;dp28;fg42;type99lmg" );
	// setDvar( "class_heavygunner_primary_attachment", "none" );
	// setDvar( "class_heavygunner_secondary", "nambu;colt;nambu;colt;tokarev;walther;nambu" );
	// setDvar( "class_heavygunner_perk1", "specialty_specialgrenade" );
	// setDvar( "class_heavygunner_perk2", "specialty_flakjacket" );
	// setDvar( "class_heavygunner_perk3", "specialty_bulletpenetration" );
	// setDvar( "class_heavygunner_perk4", "specialty_water_cooled" );
	// setDvar( "class_heavygunner_pgrenade", "frag_grenade" );
	// setDvar( "class_heavygunner_sgrenade", "tabun_gas" );
	// setDvar( "class_heavygunner_pgrenade_count", "1" );
	// setDvar( "class_heavygunner_sgrenade_count", "1" );
	// setDvar( "class_heavygunner_lock_primary", "0" );
	// setDvar( "class_heavygunner_lock_primary_attachment", "0" );
	// setDvar( "class_heavygunner_lock_secondary", "0" );
	// setDvar( "class_heavygunner_lock_perk1", "0" );
	// setDvar( "class_heavygunner_lock_perk2", "0" );
	// setDvar( "class_heavygunner_lock_perk3", "0" );
	// setDvar( "class_heavygunner_lock_perk4", "0" );
	// setDvar( "class_heavygunner_lock_pgrenade", "0" );
	// setDvar( "class_heavygunner_lock_sgrenade", "0" );
	// setDvar( "weap_allow_closeassault_shotgun", "1" );
	// setDvar( "weap_allow_closeassault_doublebarreledshotgun", "1" );
	// setDvar( "attach_allow_closeassault_none", "1" );
	// setDvar( "attach_allow_closeassault_bayonet", "1" );
	// setDvar( "attach_allow_closeassault_grip", "1" );
	// setDvar( "attach_allow_closeassault_sawoff", "1" );
	// setDvar( "class_closeassault_primary", "shotgun;shotgun;doublebarreledshotgun;shotgun;shotgun;doublebarreledshotgun;doublebarreledshotgun" );
	// setDvar( "class_closeassault_primary_attachment", "none" );
	// setDvar( "class_closeassault_secondary", "walther;colt;walther;colt;tokarev;walther;nambu" );
	// setDvar( "class_closeassault_perk1", "bazooka_mp" );
	// setDvar( "class_closeassault_perk2", "specialty_explosivedamage" );
	// setDvar( "class_closeassault_perk3", "specialty_longersprint" );
	// setDvar( "class_closeassault_perk4", "specialty_greased_barrings" );
	// setDvar( "class_closeassault_pgrenade", "sticky_grenade" );
	// setDvar( "class_closeassault_sgrenade", "tabun_gas" );
	// setDvar( "class_closeassault_pgrenade_count", "1" );
	// setDvar( "class_closeassault_sgrenade_count", "1" );
	// setDvar( "class_closeassault_lock_primary", "0" );
	// setDvar( "class_closeassault_lock_primary_attachment", "0" );
	// setDvar( "class_closeassault_lock_secondary", "0" );
	// setDvar( "class_closeassault_lock_perk1", "0" );
	// setDvar( "class_closeassault_lock_perk2", "0" );
	// setDvar( "class_closeassault_lock_perk3", "0" );
	// setDvar( "class_closeassault_lock_perk4", "0" );
	// setDvar( "class_closeassault_lock_pgrenade", "0" );
	// setDvar( "class_closeassault_lock_sgrenade", "0" );
	// setDvar( "weap_allow_sniper_springfield", "1" );
	// setDvar( "weap_allow_sniper_type99rifle", "1" );
	// setDvar( "weap_allow_sniper_mosinrifle", "1" );
	// setDvar( "weap_allow_sniper_kar98k", "1" );
	// setDvar( "weap_allow_sniper_m1garand", "1" );
	// setDvar( "weap_allow_sniper_ptrs41", "1" );
	// setDvar( "class_sniper_primary", "springfield;springfield;type99rifle;springfield;mosinrifle;kar98k;type99rifle" );
	// setDvar( "class_sniper_secondary", "colt;colt;walther;colt;tokarev;walther;nambu" );
	// setDvar( "class_sniper_perk1", "satchel_charge_mp" );
	// setDvar( "class_sniper_perk2", "specialty_bulletdamage" );
	// setDvar( "class_sniper_perk3", "specialty_bulletpenetration" );
	// setDvar( "class_sniper_perk4", "specialty_water_cooled" );
	// setDvar( "class_sniper_pgrenade", "frag_grenade" );
	// setDvar( "class_sniper_sgrenade", "m8_white_smoke" );
	// setDvar( "class_sniper_pgrenade_count", "1" );
	// setDvar( "class_sniper_sgrenade_count", "1" );
	// setDvar( "class_sniper_lock_primary", "0" );
	// setDvar( "class_sniper_lock_secondary", "0" );
	// setDvar( "class_sniper_lock_perk1", "0" );
	// setDvar( "class_sniper_lock_perk2", "0" );
	// setDvar( "class_sniper_lock_perk3", "0" );
	// setDvar( "class_sniper_lock_perk4", "0" );
	// setDvar( "class_sniper_lock_pgrenade", "0" );
	// setDvar( "class_sniper_lock_sgrenade", "0" );

	//******************************************************************************
	// configs/gameplay/fitnesscs.cfg
	//******************************************************************************
	// setDvar( "scr_fcs_enabled", "0" );
	// setDvar( "scr_fcs_crouch_on_spawn", "1" );
	// setDvar( "scr_fcs_sprint_delay", "0" );
	// setDvar( "scr_fcs_jump_allowed", "1" );
	// setDvar( "scr_fcs_jump_penalty", "40" );
	// setDvar( "scr_player_sprinttime", "4" );
	// setDvar( "scr_fcs_sprint_recovery_time", "2" );
	// setDvar( "scr_fcs_sprint_recovery_delay", "5" );
	// setDvar( "scr_fcs_sprint_slowsdown_max", "30" );
	// setDvar( "scr_fcs_walk_without_ads_allowed", "1" );
	// setDvar( "scr_fcs_pulse_enabled", "0" );
	// setDvar( "scr_fcs_pulse_modifier", "1.0" );
	
	//******************************************************************************
	// configs/gameplay/hardpoints.cfg
	//******************************************************************************
	// setDvar( "scr_game_hardpoints", "1" );
	// setDvar( "scr_hardpoint_show_reminder", "0" );
	// setDvar( "scr_remove_hardpoint_on_death", "0" );
	// setDvar( "scr_game_hardpoints_cycle", "0" );
	// setDvar( "scr_game_hardpoints_mode", "0" );
	// setDvar( "scr_announce_killstreak", "1" );
	// setDvar( "scr_hardpoint_allow_radar", "1" );
	// setDvar( "scr_game_forceradar", "0" );
	// setDvar( "scr_hardpoint_radar_streak", "3" );
	// setDvar( "scr_radar_view_time", "15" );
	// setDvar( "scr_announce_enemy_radar_online", "1" );
	// setDvar( "scr_radar_show_hardpoints", "1" );
	// setDvar( "scr_hardpoint_allow_artillery", "1" );
	// setDvar( "scr_hardpoint_artillery_streak", "5" );
	// setDvar( "scr_artillery_hardpoint_interval", "0" );
	// setDvar( "scr_announce_enemy_artillery_inbound", "1" );
	// setDvar( "scr_artillery_kills_toward_streak", "1" );
	// setDvar( "scr_artillery_delay", "0" );
	// setDvar( "scr_hardpoint_allow_dogs", "1" );
	// setDvar( "scr_hardpoint_dogs_streak", "7" );
	// setDvar( "scr_dogs_hardpoint_interval", "0" );
	// setDvar( "scr_announce_enemy_dogs_inbound", "1" );
	// setDvar( "scr_dogs_kills_toward_streak", "1" );
	// setDvar( "scr_dogs_delay", "0" );
	// setDvar( "scr_dog_time", "60" );
	// setDvar( "scr_dog_health", "100" );
	// setDvar( "scr_dog_count", "8" );
	// setDvar( "scr_dog_max_at_once", "4" );

	//******************************************************************************
	// configs/gameplay/healthsystem.cfg
	//******************************************************************************
	setDvar( "scr_player_maxhealth", "100" );
	setDvar( "scr_healthregen_method", "2" );
	setDvar( "scr_player_healthregentime", "5" );
	setDvar( "scr_health_pain_sound", "3" );
	setDvar( "scr_health_death_sound", "1" );
	setDvar( "scr_health_hurt_sound", "1" );
	// setDvar( "scr_healthsystem_show_healthbar", "0" );
	// setDvar( "scr_healthsystem_bleeding_enable", "0" );
	// setDvar( "scr_healthsystem_bleeding_percentage", "0" );
	// setDvar( "scr_healthsystem_bleeding_icon", "1" );
	// setDvar( "scr_healthsystem_bandage_start", "3" );
	// setDvar( "scr_healthsystem_bandage_max", "5" );
	// setDvar( "scr_healthsystem_bandage_self", "1" );
	// setDvar( "scr_healthsystem_bandage_time", "3" );
	// setDvar( "scr_healthsystem_medic_enable", "0" );
	// setDvar( "scr_healthsystem_medic_bandaging", "1" );
	// setDvar( "scr_healthsystem_medic_healing", "1" );
	// setDvar( "scr_healthsystem_medic_healing_self", "1" );
	// setDvar( "scr_healthsystem_medic_healing_health", "25" );
	// setDvar( "scr_healthsystem_medic_healing_time", "3" );
	// setDvar( "scr_healthsystem_medic_take_bandage", "0" );
	// setDvar( "scr_healthsystem_healing_icon", "1" );
	// setDvar( "scr_healthsystem_healthpacks_enable", "0" );
	// setDvar( "scr_healthsystem_healthpacks_timeout", "60" );
	// setDvar( "scr_healthsystem_healthpacks_health", "25" );
	// setDvar( "scr_healthsystem_healthpacks_random_health", "0" );

	//******************************************************************************
	// configs/gameplay/hud.cfg
	//******************************************************************************
	setDvar( "scr_hardcore", "0" );
	setDvar( "scr_adjust_progress_bars", "1" );
	// setDvar( "scr_show_player_assignment", "0" );
	// setDvar( "scr_enable_globalchat", "1" );
	// setDvar( "scr_enable_deadchat", "0" );
	// setDvar( "scr_show_guid_on_firstspawn", "0" );
	// setDvar( "scr_relocate_chat_position", "0" );
	// setDvar( "scr_enable_hiticon", "1" );
	// setDvar( "scr_enable_bodyarmor_feedback", "1" );
	// setDvar( "scr_hud_show_enemy_names", "1" );
	// setDvar( "scr_hud_show_friendly_names", "1" );
	// setDvar( "scr_hud_show_friendly_names_distance", "10000" );
	// setDvar( "scr_hud_show_death_icons", "1" );
	// setDvar( "scr_hud_show_redcrosshairs", "1" );
	// setDvar( "scr_hud_show_grenade_indicator", "1" );
	// setDvar( "scr_hud_show_mantle_hint", "1" );
	// setDvar( "scr_hud_show_xp_points", "1" );
	// setDvar( "scr_hud_show_center_obituary", "1" );
	// setDvar( "scr_show_obituaries", "1" );
	// setDvar( "scr_show_ext_obituaries", "0" );
	// setDvar( "scr_ext_obituaries_unit", "meters" );
	// setDvar( "scr_hud_show_scores", "1" );
	setDvar( "scr_hud_show_stance", "1" );
	// setDvar( "scr_hud_show_2dicons", "1" );
	// setDvar( "scr_hud_show_3dicons", "1" );
	// setDvar( "scr_hardcore_show_minimap", "0" );
	setDvar( "scr_hardcore_show_compass", "1" );
	// setDvar( "scr_hud_compass_objectives", "0" );
	// setDvar( "scr_minimap_show_enemies_firing", "0" );
	setDvar( "scr_blackscreen_enable", "1" );
	setDvar( "scr_blackscreen_fadetime", "3" );
	// setDvar( "scr_blackscreen_spectators", "0" );
	// setDvar( "scr_blackscreen_spectators_guids", "" );
	// setDvar( "scr_bob_effect_enable", "1" );
	// setDvar( "scr_show_general_blood_splatters", "0" );
	// setDvar( "scr_show_headshot_blood_splatters", "0" );
	// setDvar( "scr_show_knifed_blood_splatters", "0" );
	// setDvar( "scr_drawfriend", "0" );
	setDvar( "scr_hud_show_inventory", "1" );
	// setDvar( "scr_show_player_status", "1" );
	// setDvar( "scr_show_team_status", "0" );
	// setDvar( "scr_hide_scores", "0" );
	// setDvar( "scr_thirdperson_enable", "0" );
	// setDvar( "scr_realtime_stats_enable", "0" );
	// setDvar( "scr_realtime_stats_default_on", "1" );
	// setDvar( "scr_realtime_stats_unit", "meters" );

	//******************************************************************************
	// configs/gameplay/others.cfg
	//******************************************************************************
	// setDvar( "scr_team_fftype", "0" );
	// setDvar( "scr_team_teamkillpointloss", "0" );
	// setDvar( "scr_team_teamkillspawndelay", "0" );
	// setDvar( "scr_game_deathpointloss", "0" );
	// setDvar( "scr_game_suicidepointloss", "0" );
	// setDvar( "scr_player_suicidespawndelay", "0" );
	// setDvar( "scr_game_allow_killcam", "0" );
	// setDvar( "scr_player_forcerespawn", "1" );
	// setDvar( "scr_com_maxfps", "0" );
	// setDvar( "scr_cl_maxpackets", "0" );
	// setDvar( "scr_quickactions_enable", "0" );
	setDvar( "scr_fallDamageMinHeight", "175" );
	setDvar( "scr_fallDamageMaxHeight", "350" );
	// setDvar( "scr_jump_height", "39" );
	// setDvar( "scr_jump_slowdown_enable", "1" );
	// setDvar( "scr_dogtags_enable", "0" );
	setDvar( "scr_bodyremoval_enable", "2" );
	// setDvar( "scr_bodyremoval_time", "20" );
	// setDvar( "scr_vehicles_enabled", "1" );
	// setDvar( "scr_veh_health_tank", "1350" );
	// setDvar( "scr_veh_respawntimemin", "50" );
	// setDvar( "scr_veh_respawntimemax", "90" );
	// setDvar( "scr_bullet_penetration_enabled", "1" );
	// setDvar( "scr_gib_enabled", "3" );
	setDvar( "scr_enable_spawn_protection", "1" );
	// setDvar( "scr_spawn_protection_invisible", "0" );
	// setDvar( "scr_spawn_protection_time", "4" );
	// setDvar( "scr_spawn_protection_hiticon", "1" );
	// setDvar( "scr_spawn_protection_maxdistance", "0" );
	// setDvar( "scr_spawn_protection_punishment_time", "0" );
	// setDvar( "scr_enable_anti_bunny_hopping", "0" );
	// setDvar( "scr_enable_anti_dolphin_dive", "0" );
	// setDvar( "scr_anti_camping_enable", "0" );
	// setDvar( "scr_anti_camping_show", "0" );
	// setDvar( "scr_anti_camping_message", "" );
	// setDvar( "scr_anti_camping_distance", "100" );
	// setDvar( "scr_anti_camping_time", "60" );
	// setDvar( "scr_de_dropweapon_on_arm_hit", "0" );
	// setDvar( "scr_de_dropweapon_chance", "50" );
	// setDvar( "scr_de_falldown_on_leg_hit", "0" );
	// setDvar( "scr_de_falldown_chance", "50" );
	// setDvar( "scr_de_shiftview_on_damage", "0" );
	// setDvar( "scr_de_break_ankle_on_fall", "0" );
	// setDvar( "scr_de_slowdown_on_leg_hit", "0" );
	// setDvar( "scr_cap_enable", "0" );
	// setDvar( "scr_cap_time", "5.0" );
	// setDvar( "scr_cap_firstspawn", "0" );

	//******************************************************************************
	// configs/gameplay/perks.cfg
	//******************************************************************************
	// setDvar( "perk_allow_specialty_specialgrenade", "1" );
	// setDvar( "perk_allow_specialty_weapon_bouncing_betty", "1" );
	// setDvar( "perk_allow_specialty_fraggrenade", "1" );
	// setDvar( "perk_allow_specialty_extraammo", "1" );
	// setDvar( "perk_allow_specialty_detectexplosive", "1" );
	// setDvar( "perk_allow_specialty_weapon_flamethrower", "1" );
	// setDvar( "perk_allow_specialty_weapon_bazooka", "1" );
	// setDvar( "perk_allow_specialty_weapon_satchel_charge", "1" );
	// setDvar( "perk_specialty_weapon_bouncing_betty_limit", "64" );
	// setDvar( "perk_specialty_weapon_flamethrower_limit", "64" );
	// setDvar( "perk_specialty_weapon_bazooka_limit", "64" );
	// setDvar( "perk_specialty_weapon_satchel_charge_limit", "64" );
	// setDvar( "specialty_fraggrenade_ammo_count", "2" );
	// setDvar( "specialty_specialgrenade_ammo_count", "2" );
	// setDvar( "perk_allow_specialty_bulletdamage", "1" );
	// setDvar( "perk_allow_specialty_armorvest", "1" );
	// setDvar( "perk_allow_specialty_fastreload", "1" );
	// setDvar( "perk_allow_specialty_rof", "1" );
	// setDvar( "perk_allow_specialty_twoprimaries", "1" );
	// setDvar( "perk_allow_specialty_gpsjammer", "1" );
	// setDvar( "perk_allow_specialty_explosivedamage", "1" );
	// setDvar( "perk_allow_specialty_flakjacket", "1" );
	// setDvar( "perk_allow_specialty_shades", "1" );
	// setDvar( "perk_allow_specialty_gas_mask", "1" );
	// setDvar( "perk_armorvest", "75" );
	// setDvar( "perk_bulletdamage", "40" );
	// setDvar( "perk_explosivedamage", "25" );
	// setDvar( "perk_flakjacket", "75" );
	// setDvar( "perk_flakjacketmaxdamage", "75" );
	// setDvar( "perk_allow_specialty_longersprint", "1" );
	// setDvar( "perk_allow_specialty_bulletaccuracy", "1" );
	// setDvar( "perk_allow_specialty_pistoldeath", "1" );
	// setDvar( "perk_allow_specialty_grenadepulldeath", "1" );
	// setDvar( "perk_allow_specialty_bulletpenetration", "1" );
	// setDvar( "perk_allow_specialty_holdbreath", "1" );
	// setDvar( "perk_allow_specialty_quieter", "1" );
	// setDvar( "perk_allow_specialty_fireproof", "1" );
	// setDvar( "perk_allow_specialty_reconnaissance", "1" );
	// setDvar( "perk_allow_specialty_pin_back", "1" );
	setDvar( "specialty_grenadepulldeath_check_frags", "1" );
	setDvar( "specialty_pistoldeath_check_pistol", "1" );
	// setDvar( "specialty_pistoldeath_no_weapons", "0" );
	// setDvar( "perk_fireproof", "55" );
	// setDvar( "perk_allow_specialty_water_cooled", "1" );
	// setDvar( "perk_allow_specialty_greased_barrings", "1" );
	// setDvar( "perk_allow_specialty_ordinance", "1" );
	// setDvar( "perk_allow_specialty_boost", "1" );
	// setDvar( "perk_allow_specialty_leadfoot", "1" );
	// setDvar( "perk_grenadier_allow_specialty_specialgrenade", "1" );
	// setDvar( "perk_rifleman_allow_specialty_specialgrenade", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_specialgrenade", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_specialgrenade", "1" );
	// setDvar( "perk_closeassault_allow_specialty_specialgrenade", "1" );
	// setDvar( "perk_sniper_allow_specialty_specialgrenade", "1" );
	// setDvar( "perk_grenadier_allow_specialty_weapon_bouncing_betty", "1" );
	// setDvar( "perk_rifleman_allow_specialty_weapon_bouncing_betty", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_weapon_bouncing_betty", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_weapon_bouncing_betty", "1" );
	// setDvar( "perk_closeassault_allow_specialty_weapon_bouncing_betty", "1" );
	// setDvar( "perk_sniper_allow_specialty_weapon_bouncing_betty", "1" );
	// setDvar( "perk_grenadier_allow_specialty_fraggrenade", "1" );
	// setDvar( "perk_rifleman_allow_specialty_fraggrenade", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_fraggrenade", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_fraggrenade", "1" );
	// setDvar( "perk_closeassault_allow_specialty_fraggrenade", "1" );
	// setDvar( "perk_sniper_allow_specialty_fraggrenade", "1" );
	// setDvar( "perk_grenadier_allow_specialty_extraammo", "1" );
	// setDvar( "perk_rifleman_allow_specialty_extraammo", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_extraammo", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_extraammo", "1" );
	// setDvar( "perk_closeassault_allow_specialty_extraammo", "1" );
	// setDvar( "perk_sniper_allow_specialty_extraammo", "1" );
	// setDvar( "perk_grenadier_allow_specialty_detectexplosive", "1" );
	// setDvar( "perk_rifleman_allow_specialty_detectexplosive", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_detectexplosive", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_detectexplosive", "1" );
	// setDvar( "perk_closeassault_allow_specialty_detectexplosive", "1" );
	// setDvar( "perk_sniper_allow_specialty_detectexplosive", "1" );
	// setDvar( "perk_grenadier_allow_specialty_weapon_flamethrower", "1" );
	// setDvar( "perk_rifleman_allow_specialty_weapon_flamethrower", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_weapon_flamethrower", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_weapon_flamethrower", "1" );
	// setDvar( "perk_closeassault_allow_specialty_weapon_flamethrower", "1" );
	// setDvar( "perk_sniper_allow_specialty_weapon_flamethrower", "1" );
	// setDvar( "perk_grenadier_allow_specialty_weapon_bazooka", "1" );
	// setDvar( "perk_rifleman_allow_specialty_weapon_bazooka", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_weapon_bazooka", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_weapon_bazooka", "1" );
	// setDvar( "perk_closeassault_allow_specialty_weapon_bazooka", "1" );
	// setDvar( "perk_sniper_allow_specialty_weapon_bazooka", "1" );
	// setDvar( "perk_grenadier_allow_specialty_weapon_satchel_charge", "1" );
	// setDvar( "perk_rifleman_allow_specialty_weapon_satchel_charge", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_weapon_satchel_charge", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_weapon_satchel_charge", "1" );
	// setDvar( "perk_closeassault_allow_specialty_weapon_satchel_charge", "1" );
	// setDvar( "perk_sniper_allow_specialty_weapon_satchel_charge", "1" );
	// setDvar( "perk_grenadier_allow_specialty_bulletdamage", "1" );
	// setDvar( "perk_rifleman_allow_specialty_bulletdamage", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_bulletdamage", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_bulletdamage", "1" );
	// setDvar( "perk_closeassault_allow_specialty_bulletdamage", "1" );
	// setDvar( "perk_sniper_allow_specialty_bulletdamage", "1" );
	// setDvar( "perk_grenadier_allow_specialty_armorvest", "1" );
	// setDvar( "perk_rifleman_allow_specialty_armorvest", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_armorvest", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_armorvest", "1" );
	// setDvar( "perk_closeassault_allow_specialty_armorvest", "1" );
	// setDvar( "perk_sniper_allow_specialty_armorvest", "1" );
	// setDvar( "perk_grenadier_allow_specialty_fastreload", "1" );
	// setDvar( "perk_rifleman_allow_specialty_fastreload", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_fastreload", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_fastreload", "1" );
	// setDvar( "perk_closeassault_allow_specialty_fastreload", "1" );
	// setDvar( "perk_sniper_allow_specialty_fastreload", "1" );
	// setDvar( "perk_grenadier_allow_specialty_rof", "1" );
	// setDvar( "perk_rifleman_allow_specialty_rof", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_rof", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_rof", "1" );
	// setDvar( "perk_closeassault_allow_specialty_rof", "1" );
	// setDvar( "perk_sniper_allow_specialty_rof", "1" );
	// setDvar( "perk_grenadier_allow_specialty_twoprimaries", "1" );
	// setDvar( "perk_rifleman_allow_specialty_twoprimaries", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_twoprimaries", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_twoprimaries", "1" );
	// setDvar( "perk_closeassault_allow_specialty_twoprimaries", "1" );
	// setDvar( "perk_sniper_allow_specialty_twoprimaries", "1" );
	// setDvar( "perk_grenadier_allow_specialty_gpsjammer", "1" );
	// setDvar( "perk_rifleman_allow_specialty_gpsjammer", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_gpsjammer", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_gpsjammer", "1" );
	// setDvar( "perk_closeassault_allow_specialty_gpsjammer", "1" );
	// setDvar( "perk_sniper_allow_specialty_gpsjammer", "1" );
	// setDvar( "perk_grenadier_allow_specialty_explosivedamage", "1" );
	// setDvar( "perk_rifleman_allow_specialty_explosivedamage", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_explosivedamage", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_explosivedamage", "1" );
	// setDvar( "perk_closeassault_allow_specialty_explosivedamage", "1" );
	// setDvar( "perk_sniper_allow_specialty_explosivedamage", "1" );
	// setDvar( "perk_grenadier_allow_specialty_flakjacket", "1" );
	// setDvar( "perk_rifleman_allow_specialty_flakjacket", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_flakjacket", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_flakjacket", "1" );
	// setDvar( "perk_closeassault_allow_specialty_flakjacket", "1" );
	// setDvar( "perk_sniper_allow_specialty_flakjacket", "1" );
	// setDvar( "perk_grenadier_allow_specialty_shades", "1" );
	// setDvar( "perk_rifleman_allow_specialty_shades", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_shades", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_shades", "1" );
	// setDvar( "perk_closeassault_allow_specialty_shades", "1" );
	// setDvar( "perk_sniper_allow_specialty_shades", "1" );
	// setDvar( "perk_grenadier_allow_specialty_gas_mask", "1" );
	// setDvar( "perk_rifleman_allow_specialty_gas_mask", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_gas_mask", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_gas_mask", "1" );
	// setDvar( "perk_closeassault_allow_specialty_gas_mask", "1" );
	// setDvar( "perk_sniper_allow_specialty_gas_mask", "1" );
	// setDvar( "perk_grenadier_allow_specialty_longersprint", "1" );
	// setDvar( "perk_rifleman_allow_specialty_longersprint", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_longersprint", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_longersprint", "1" );
	// setDvar( "perk_closeassault_allow_specialty_longersprint", "1" );
	// setDvar( "perk_sniper_allow_specialty_longersprint", "1" );
	// setDvar( "perk_grenadier_allow_specialty_bulletaccuracy", "1" );
	// setDvar( "perk_rifleman_allow_specialty_bulletaccuracy", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_bulletaccuracy", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_bulletaccuracy", "1" );
	// setDvar( "perk_closeassault_allow_specialty_bulletaccuracy", "1" );
	// setDvar( "perk_sniper_allow_specialty_bulletaccuracy", "1" );
	// setDvar( "perk_grenadier_allow_specialty_pistoldeath", "1" );
	// setDvar( "perk_rifleman_allow_specialty_pistoldeath", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_pistoldeath", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_pistoldeath", "1" );
	// setDvar( "perk_closeassault_allow_specialty_pistoldeath", "1" );
	// setDvar( "perk_sniper_allow_specialty_pistoldeath", "1" );
	// setDvar( "perk_grenadier_allow_specialty_grenadepulldeath", "1" );
	// setDvar( "perk_rifleman_allow_specialty_grenadepulldeath", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_grenadepulldeath", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_grenadepulldeath", "1" );
	// setDvar( "perk_closeassault_allow_specialty_grenadepulldeath", "1" );
	// setDvar( "perk_sniper_allow_specialty_grenadepulldeath", "1" );
	// setDvar( "perk_grenadier_allow_specialty_bulletpenetration", "1" );
	// setDvar( "perk_rifleman_allow_specialty_bulletpenetration", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_bulletpenetration", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_bulletpenetration", "1" );
	// setDvar( "perk_closeassault_allow_specialty_bulletpenetration", "1" );
	// setDvar( "perk_sniper_allow_specialty_bulletpenetration", "1" );
	// setDvar( "perk_grenadier_allow_specialty_holdbreath", "1" );
	// setDvar( "perk_rifleman_allow_specialty_holdbreath", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_holdbreath", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_holdbreath", "1" );
	// setDvar( "perk_closeassault_allow_specialty_holdbreath", "1" );
	// setDvar( "perk_sniper_allow_specialty_holdbreath", "1" );
	// setDvar( "perk_grenadier_allow_specialty_quieter", "1" );
	// setDvar( "perk_rifleman_allow_specialty_quieter", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_quieter", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_quieter", "1" );
	// setDvar( "perk_closeassault_allow_specialty_quieter", "1" );
	// setDvar( "perk_sniper_allow_specialty_quieter", "1" );
	// setDvar( "perk_grenadier_allow_specialty_fireproof", "1" );
	// setDvar( "perk_rifleman_allow_specialty_fireproof", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_fireproof", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_fireproof", "1" );
	// setDvar( "perk_closeassault_allow_specialty_fireproof", "1" );
	// setDvar( "perk_sniper_allow_specialty_fireproof", "1" );
	// setDvar( "perk_grenadier_allow_specialty_reconnaissance", "1" );
	// setDvar( "perk_rifleman_allow_specialty_reconnaissance", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_reconnaissance", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_reconnaissance", "1" );
	// setDvar( "perk_closeassault_allow_specialty_reconnaissance", "1" );
	// setDvar( "perk_sniper_allow_specialty_reconnaissance", "1" );
	// setDvar( "perk_grenadier_allow_specialty_pin_back", "1" );
	// setDvar( "perk_rifleman_allow_specialty_pin_back", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_pin_back", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_pin_back", "1" );
	// setDvar( "perk_closeassault_allow_specialty_pin_back", "1" );
	// setDvar( "perk_sniper_allow_specialty_pin_back", "1" );
	// setDvar( "perk_grenadier_allow_specialty_water_cooled", "1" );
	// setDvar( "perk_rifleman_allow_specialty_water_cooled", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_water_cooled", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_water_cooled", "1" );
	// setDvar( "perk_closeassault_allow_specialty_water_cooled", "1" );
	// setDvar( "perk_sniper_allow_specialty_water_cooled", "1" );
	// setDvar( "perk_grenadier_allow_specialty_greased_barrings", "1" );
	// setDvar( "perk_rifleman_allow_specialty_greased_barrings", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_greased_barrings", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_greased_barrings", "1" );
	// setDvar( "perk_closeassault_allow_specialty_greased_barrings", "1" );
	// setDvar( "perk_sniper_allow_specialty_greased_barrings", "1" );
	// setDvar( "perk_grenadier_allow_specialty_ordinance", "1" );
	// setDvar( "perk_rifleman_allow_specialty_ordinance", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_ordinance", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_ordinance", "1" );
	// setDvar( "perk_closeassault_allow_specialty_ordinance", "1" );
	// setDvar( "perk_sniper_allow_specialty_ordinance", "1" );
	// setDvar( "perk_grenadier_allow_specialty_boost", "1" );
	// setDvar( "perk_rifleman_allow_specialty_boost", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_boost", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_boost", "1" );
	// setDvar( "perk_closeassault_allow_specialty_boost", "1" );
	// setDvar( "perk_sniper_allow_specialty_boost", "1" );
	// setDvar( "perk_grenadier_allow_specialty_leadfoot", "1" );
	// setDvar( "perk_rifleman_allow_specialty_leadfoot", "1" );
	// setDvar( "perk_lightgunner_allow_specialty_leadfoot", "1" );
	// setDvar( "perk_heavygunner_allow_specialty_leadfoot", "1" );
	// setDvar( "perk_closeassault_allow_specialty_leadfoot", "1" );
	// setDvar( "perk_sniper_allow_specialty_leadfoot", "1" );

	//******************************************************************************
	// configs/gameplay/scores.cfg
	//******************************************************************************
	// setDvar( "scr_enable_scoresystem", "0" );
	// setDvar( "scr_score_tk_affects_teamscore", "0" );
	// setDvar( "scr_score_standard_kill", "10" );
	// setDvar( "scr_score_headshot_kill", "10" );
	// setDvar( "scr_score_melee_kill", "10" );
	// setDvar( "scr_score_grenade_kill", "10" );
	// setDvar( "scr_score_satchel_kill", "10" );
	// setDvar( "scr_score_betty_kill", "10" );
	// setDvar( "scr_score_rpg_kill", "10" );
	// setDvar( "scr_score_grenade_launcher_kill", "10" );
	// setDvar( "scr_score_flamethrower_kill", "10" );
	// setDvar( "scr_score_knock_over_kill", "10" );
	// setDvar( "scr_score_tank_grenade_kill", "10" );
	// setDvar( "scr_score_artillery_kill", "10" );
	// setDvar( "scr_score_dog_kill", "10" );
	// setDvar( "scr_score_vehicle_explosion_kill", "10" );
	// setDvar( "scr_score_barrel_explosion_kill", "10" );
	// setDvar( "scr_score_assist_kill", "2" );
	// setDvar( "scr_score_assist_25_kill", "3" );
	// setDvar( "scr_score_assist_50_kill", "4" );
	// setDvar( "scr_score_assist_75_kill", "5" );
	// setDvar( "scr_score_player_death", "0" );
	// setDvar( "scr_score_player_suicide", "0" );
	// setDvar( "scr_score_player_teamkill", "-5" );
	// setDvar( "scr_score_hardpoint_used", "10" );
	// setDvar( "scr_score_shot_down_helicopter", "0" );
	// setDvar( "scr_score_capture_objective", "30" );
	// setDvar( "scr_score_take_objective", "7" );
	// setDvar( "scr_score_return_objective", "7" );
	// setDvar( "scr_score_defend_objective", "30" );
	// setDvar( "scr_score_holding_objective", "2" );
	// setDvar( "scr_score_kill_objective_carrier", "5" );
	// setDvar( "scr_score_assault_objective", "5" );
	// setDvar( "scr_score_plant_bomb", "20" );
	// setDvar( "scr_score_defuse_bomb", "15" );

	//******************************************************************************
	// configs/gameplay/sounds.cfg
	//******************************************************************************
	// setDvar( "scr_sound_occlusion_enable", "1" );
	// setDvar( "scr_tactical_enable", "0" );
	// setDvar( "scr_countdown_sounds", "" );
	// setDvar( "scr_play_headshot_impact_sound", "1" );
	// setDvar( "scr_unreal_firstblood_sound", "0" );
	// setDvar( "scr_unreal_headshot_sound", "0" );
	// setDvar( "scr_killingspree_enable", "0" );
	// setDvar( "scr_killingspree_sounds", "2 doublekill;5 killingspree;7 rampage;9 dominating;12 unstoppable;15 godlike" );
	// setDvar( "scr_allowbattlechatter", "1" );
	// setDvar( "scr_battlechatter_reload_probability", "75" );
	// setDvar( "scr_battlechatter_frag_out_probability", "75" );
	// setDvar( "scr_battlechatter_sticky_out_probability", "75" );
	// setDvar( "scr_battlechatter_flare_out_probability", "75" );
	// setDvar( "scr_battlechatter_smoke_out_probability", "75" );
	// setDvar( "scr_battlechatter_molotov_out_probability", "75" );
	// setDvar( "scr_battlechatter_gas_out_probability", "75" );
	// setDvar( "scr_battlechatter_satchel_planted_probability", "75" );
	// setDvar( "scr_battlechatter_betty_planted_probability", "75" );
	// setDvar( "scr_battlechatter_kill_probability", "75" );

	//******************************************************************************
	// configs/gameplay/spectate.cfg
	//******************************************************************************
	setDvar( "scr_game_spectatetype", "1" );
	setDvar( "scr_game_spectatetype_dm", "0" );
	setDvar( "scr_game_spectatetype_gg", "0" );
	setDvar( "scr_game_spectatetype_spectators", "2" );
	// setDvar( "scr_game_spectators_guids", "" );
	// setDvar( "scr_allow_thirdperson", "0" );
	// setDvar( "scr_allow_thirdperson_guids", "" );	

	//******************************************************************************
	// configs/gameplay/visuals.cfg
	//******************************************************************************
	// setDvar( "scr_map_special_fx_enable", "1" );
	// setDvar( "scr_show_fog", "1" );
	// setDvar( "scr_dcs_enabled", "0" );
	// setDvar( "scr_dcs_dawn_length", "10" );
	// setDvar( "scr_dcs_day_length", "20" );
	// setDvar( "scr_dcs_dusk_length", "10" );
	// setDvar( "scr_dcs_night_length", "20" );
	// setDvar( "scr_dcs_first_cycle", "1" );
	// setDvar( "scr_dcs_sounds_enable", "1" );
	// setDvar( "scr_dcs_reset_cycle", "0" );
	
	//******************************************************************************
	// configs/gameplay/wdm.cfg
	//******************************************************************************
	// setDvar( "scr_wdm_enabled", "0" );
	// setDvar( "scr_wdm_springfield", "100" );
	// setDvar( "scr_wdm_type99rifle", "100" );
	// setDvar( "scr_wdm_mosinrifle", "100" );
	// setDvar( "scr_wdm_kar98k", "100" );
	// setDvar( "scr_wdm_ptrs41", "100" );
	// setDvar( "scr_wdm_svt40", "100" );
	// setDvar( "scr_wdm_svt40_silenced", "100" );
	// setDvar( "scr_wdm_gewehr43", "100" );
	// setDvar( "scr_wdm_gewehr43_silenced", "100" );
	// setDvar( "scr_wdm_m1garand", "100" );
	// setDvar( "scr_wdm_m1garand_silenced", "100" );
	// setDvar( "scr_wdm_stg44", "100" );
	// setDvar( "scr_wdm_stg44_silenced", "100" );
	// setDvar( "scr_wdm_m1carbine", "100" );
	// setDvar( "scr_wdm_m1carbine_silenced", "100" );
	// setDvar( "scr_wdm_thompson", "100" );
	// setDvar( "scr_wdm_thompson_silenced", "100" );
	// setDvar( "scr_wdm_mp40", "100" );
	// setDvar( "scr_wdm_mp40_silenced", "100" );
	// setDvar( "scr_wdm_type100smg", "100" );
	// setDvar( "scr_wdm_type100smg_silenced", "100" );
	// setDvar( "scr_wdm_ppsh", "100" );
	// setDvar( "scr_wdm_shotgun", "100" );
	// setDvar( "scr_wdm_doublebarreledshotgun", "100" );
	// setDvar( "scr_wdm_type99lmg", "100" );
	// setDvar( "scr_wdm_bar", "100" );
	// setDvar( "scr_wdm_dp28", "100" );
	// setDvar( "scr_wdm_mg42", "100" );
	// setDvar( "scr_wdm_fg42", "100" );
	// setDvar( "scr_wdm_30cal", "100" );
	// setDvar( "scr_wdm_colt", "100" );
	// setDvar( "scr_wdm_nambu", "100" );
	// setDvar( "scr_wdm_walther", "100" );
	// setDvar( "scr_wdm_tokarev", "100" );
	// setDvar( "scr_wdm_357magnum", "100" );
	// setDvar( "scr_wdm_frag_grenades", "100" );
	// setDvar( "scr_wdm_sticky_grenades", "100" );
	// setDvar( "scr_wdm_molotovs", "100" );
	// setDvar( "scr_wdm_gl", "100" );
	// setDvar( "scr_wdm_satchels", "100" );
	// setDvar( "scr_wdm_bettys", "100" );
	// setDvar( "scr_wdm_bazookas", "100" );
	// setDvar( "scr_wdm_vehicles", "100" );
	// setDvar( "scr_wdm_barrels", "100" );

	//******************************************************************************
	// configs/gameplay/weapons.cfg
	//******************************************************************************					
	// setDvar( "scr_dynamic_attachments_enable", "0" );
	setDvar( "scr_deleteexplosivesonspawn", "1" );
	// setDvar( "scr_deleteexplosivesondeath", "0" );
	// setDvar( "scr_explosives_allow_disarm", "0" );
	// setDvar( "scr_explosives_disarm_time", "5" );
	// setDvar( "scr_betty_show_headicon", "1" );
	// setDvar( "scr_betty_detonate_radius", "150" );
	// setDvar( "scr_betty_arm_time", "0" );
	// setDvar( "scr_betty_check_plant_distance", "0" );
	setDvar( "scr_betty_line_of_sight", "1" );
	// setDvar( "scr_betty_show_glow", "1" );
	// setDvar( "scr_betty_friendly_fire", "0" );
	// setDvar( "scr_allow_stationary_turrets", "1" );
	// setDvar( "scr_delay_frag_grenades", "0" );
	// setDvar( "scr_delay_sticky_grenades", "0" );
	// setDvar( "scr_delay_molotovs", "0" );
	// setDvar( "scr_delay_grenade_launchers", "0" );
	// setDvar( "scr_delay_smoke_grenades", "0" );
	// setDvar( "scr_delay_signal_flares", "0" );
	// setDvar( "scr_delay_tabun_gas_grenades", "0" );
	// setDvar( "scr_delay_bazookas", "0" );
	// setDvar( "scr_delay_satchels", "0" );
	// setDvar( "scr_delay_bettys", "0" );
	// setDvar( "scr_delay_flamethrower", "0" );
	// setDvar( "scr_delay_only_round_start", "1" );
	// setDvar( "scr_delay_sound_enable", "1" );
	// setDvar( "scr_tabun_gas_poisonous", "0" );
	// setDvar( "scr_enable_auto_melee", "1" );
	// setDvar( "scr_limit_planted_bettys", "0" );
	// setDvar( "scr_limit_planted_satchels", "0" );
	// setDvar( "scr_fire_tracer_chance", "0" );
	// setDvar( "scr_barrel_damage_enable", "1" );
	// setDvar( "scr_vehicle_damage_enable", "1" );
	// setDvar( "scr_rng_enabled", "0" );
	// setDvar( "scr_rng_distance", "200" );
	// setDvar( "scr_rng_damage_closer", "50" );
	// setDvar( "scr_rng_damage_longer", "5" );
	// setDvar( "scr_weaponjams_enable", "0" );
	// setDvar( "scr_weaponjams_probability", "250" );
	// setDvar( "scr_weaponjams_gap_time", "0" );
	// setDvar( "scr_sniperzoom_enable", "0" );
	// setDvar( "scr_sniperzoom_lower_levels", "8" );
	// setDvar( "scr_sniperzoom_upper_levels", "9" );
	// setDvar( "scr_rangefinder_enable", "0" );
	// setDvar( "scr_objective_safezone_enable", "0" );
	// setDvar( "scr_objective_safezone_radius", "100" );
	
	//******************************************************************************
	// configs/gameplay/wlm.cfg
	//******************************************************************************
	// setDvar( "scr_wlm_enabled", "0" );
	// setDvar( "scr_wlm_upper_arm", "100" );
	// setDvar( "scr_wlm_lower_arm", "100" );
	// setDvar( "scr_wlm_hand", "100" );
	// setDvar( "scr_wlm_upper_leg", "100" );
	// setDvar( "scr_wlm_lower_leg", "100" );
	// setDvar( "scr_wlm_foot", "100" );
	// setDvar( "scr_wlm_head", "100" );
	// setDvar( "scr_wlm_neck", "100" );
	// setDvar( "scr_wlm_upper_torso", "100" );
	// setDvar( "scr_wlm_lower_torso", "100" );
	
	//******************************************************************************
	// configs/gameplay/wrm.cfg
	//******************************************************************************
	// setDvar( "scr_wrm_enabled", "0" );
	// setDvar( "scr_wrm_springfield", "215" );
	// setDvar( "scr_wrm_type99rifle", "215" );
	// setDvar( "scr_wrm_mosinrifle", "215" );
	// setDvar( "scr_wrm_kar98k", "215" );
	// setDvar( "scr_wrm_ptrs41", "215" );
	// setDvar( "scr_wrm_svt40", "215" );
	// setDvar( "scr_wrm_svt40_silenced", "215" );
	// setDvar( "scr_wrm_gewehr43", "215" );
	// setDvar( "scr_wrm_gewehr43_silenced", "215" );
	// setDvar( "scr_wrm_m1garand", "215" );
	// setDvar( "scr_wrm_m1garand_silenced", "215" );
	// setDvar( "scr_wrm_stg44", "215" );
	// setDvar( "scr_wrm_stg44_silenced", "215" );
	// setDvar( "scr_wrm_m1carbine", "215" );
	// setDvar( "scr_wrm_m1carbine_silenced", "215" );
	// setDvar( "scr_wrm_thompson", "215" );
	// setDvar( "scr_wrm_thompson_silenced", "215" );
	// setDvar( "scr_wrm_mp40", "215" );
	// setDvar( "scr_wrm_mp40_silenced", "215" );
	// setDvar( "scr_wrm_type100smg", "215" );
	// setDvar( "scr_wrm_type100smg_silenced", "215" );
	// setDvar( "scr_wrm_ppsh", "215" );
	// setDvar( "scr_wrm_shotgun", "215" );
	// setDvar( "scr_wrm_doublebarreledshotgun", "215" );
	// setDvar( "scr_wrm_type99lmg", "215" );
	// setDvar( "scr_wrm_bar", "215" );
	// setDvar( "scr_wrm_dp28", "215" );
	// setDvar( "scr_wrm_mg42", "215" );
	// setDvar( "scr_wrm_fg42", "215" );
	// setDvar( "scr_wrm_30cal", "215" );
	// setDvar( "scr_wrm_colt", "215" );
	// setDvar( "scr_wrm_nambu", "215" );
	// setDvar( "scr_wrm_walther", "215" );
	// setDvar( "scr_wrm_tokarev", "215" );
	// setDvar( "scr_wrm_357magnum", "215" );
	
	//******************************************************************************
	// configs/gameplay/wwm.cfg
	//******************************************************************************
	// setDvar( "scr_wwm_enabled", "0" );
	// setDvar( "scr_wwm_range_weight_1", "1.0" );
	// setDvar( "scr_wwm_range_speed_1", "1.10" );
	// setDvar( "scr_wwm_range_weight_2", "3.0" );
	// setDvar( "scr_wwm_range_speed_2", "1.00" );
	// setDvar( "scr_wwm_range_weight_3", "6.0" );
	// setDvar( "scr_wwm_range_speed_3", "0.80" );
	// setDvar( "scr_wwm_range_weight_4", "8.0" );
	// setDvar( "scr_wwm_range_speed_4", "0.70" );
	// setDvar( "scr_wwm_range_weight_5", "20.0" );
	// setDvar( "scr_wwm_range_speed_5", "0.60" );
	// setDvar( "scr_wwm_springfield", "4" );
	// setDvar( "scr_wwm_type99rifle", "4" );
	// setDvar( "scr_wwm_mosinrifle", "4" );
	// setDvar( "scr_wwm_kar98k", "4" );
	// setDvar( "scr_wwm_ptrs41", "4" );
	// setDvar( "scr_wwm_springfield_gl", "5" );
	// setDvar( "scr_wwm_type99rifle_gl", "5" );
	// setDvar( "scr_wwm_mosinrifle_gl", "5" );
	// setDvar( "scr_wwm_kar98k_gl", "5" );
	// setDvar( "scr_wwm_svt40", "4" );
	// setDvar( "scr_wwm_gewehr43", "4" );
	// setDvar( "scr_wwm_m1garand", "4" );
	// setDvar( "scr_wwm_stg44", "4" );
	// setDvar( "scr_wwm_m1carbine", "4" );
	// setDvar( "scr_wwm_gewehr43_gl", "5" );
	// setDvar( "scr_wwm_m1garand_gl", "5" );
	// setDvar( "scr_wwm_thompson", "3" );
	// setDvar( "scr_wwm_mp40", "3" );
	// setDvar( "scr_wwm_type100smg", "3" );
	// setDvar( "scr_wwm_ppsh", "3" );
	// setDvar( "scr_wwm_shotgun", "4" );
	// setDvar( "scr_wwm_doublebarreledshotgun", "4" );
	// setDvar( "scr_wwm_type99lmg", "9" );
	// setDvar( "scr_wwm_bar", "9" );
	// setDvar( "scr_wwm_dp28", "9" );
	// setDvar( "scr_wwm_mg42", "9" );
	// setDvar( "scr_wwm_fg42", "9" );
	// setDvar( "scr_wwm_30cal", "9" );
	// setDvar( "scr_wwm_type99lmg_bipod", "10" );
	// setDvar( "scr_wwm_bar_bipod", "10" );
	// setDvar( "scr_wwm_dp28_bipod", "10" );
	// setDvar( "scr_wwm_mg42_bipod", "10" );
	// setDvar( "scr_wwm_fg42_bipod", "10" );
	// setDvar( "scr_wwm_30cal_bipod", "10" );
	// setDvar( "scr_wwm_colt", "0.5" );
	// setDvar( "scr_wwm_nambu", "0.5" );
	// setDvar( "scr_wwm_walther", "0.5" );
	// setDvar( "scr_wwm_tokarev", "1" );
	// setDvar( "scr_wwm_357magnum", "1" );
	// setDvar( "scr_wwm_bomb", "2" );
	// setDvar( "scr_wwm_frag_grenade", "1" );
	// setDvar( "scr_wwm_sticky_grenade", "1" );
	// setDvar( "scr_wwm_molotov", "1" );
	// setDvar( "scr_wwm_signal_flare", "1" );
	// setDvar( "scr_wwm_smoke_grenade", "1" );
	// setDvar( "scr_wwm_tabun_gas_grenade", "1" );
	// setDvar( "scr_wwm_satchel", "2" );
	// setDvar( "scr_wwm_betty", "2" );
	// setDvar( "scr_wwm_bazooka", "5" );
}